### PR TITLE
it returns null when promise getter returns null

### LINKED ISSUE #2: Fails when promiseGetter returns null
These lines fail https://github.com/canjs/can-stache-key/blob/master/can-stache-key.js#L190-L192

when a promise getter returns null, because typeof null is 'object' and `null.then` causes an error. 

Example, I might not want to return a promise when there is no id to view, so I return null:

```javascript
    focusObjectPromise: {
        get () {
            if (this.viewId) {
                const params = {};
                params[this.view.connection.idProp] = this.viewId;
                const promise = this.view.connection.get(params);

                promise.catch((err) => {
                    dev.warn('unable to complete focusObject request', err);
                });

                return promise;
            }
            return null;
        }
    },
```

### PR DESCRIPTION
**Pull request by cherifGsoul**
fixes #2

### CODE REVIEW

**Comment by phillipskevin** [comment]
@justinbmeyer can you release a patch for this when you get a chance?

**Comment by jeroencornelissen** [comment]
Is this bug already released? I think `can-component` still depends on `0.0.2`.
This is throwing a lot of errors in our production app.

**Comment by cherifGsoul** [comment]
@jeroencornelissen not released yet.

**Comment by phillipskevin** [comment]
Thanks for pointing this out. I will release patches with the updated version for everything that depends on this.

**Comment by phillipskevin** [comment]
Patches are out with this change. If you update to the latest, everything should be using can-stache-key 0.0.4:

```
$ npm ls can-stache-key
can@3.9.0 /Users/kevin/dev/canjs
├─┬ can-component@3.3.1
│ └── can-stache-key@0.0.4  deduped
├─┬ can-compute@3.3.2
│ └── can-stache-key@0.0.4  deduped
├─┬ can-control@3.2.1
│ └── can-stache-key@0.0.4  deduped
├─┬ can-ejs@3.1.3
│ └── can-stache-key@0.0.4  deduped
├─┬ can-map@3.3.2
│ └── can-stache-key@0.0.4  deduped
├─┬ can-stache@3.3.4
│ └── can-stache-key@0.0.4  deduped
├─┬ can-stache-bindings@3.4.7
│ └── can-stache-key@0.0.4  deduped
├── can-stache-key@0.0.4
└─┬ can-view-scope@3.3.3
  └── can-stache-key@0.0.4  deduped
```

**Pull request merged**
